apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-servicemonitor
  namespace: database  # Redis가 설치된 네임스페이스
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster
  namespaceSelector:
    matchNames:
    - database  # Redis가 설치된 네임스페이스
  endpoints:
  - port: metrics
    interval: 30s