serviceMonitor:
  enabled: true
  labels:
    release: prometheus
  namespace: logging
  interval: 30s

es:
  uri: http://elasticsearch-master:9200
  # timeout: 30s
  # sslSkipVerify: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi