cluster:
  nodes: 6
  replicas: 1

persistence:
  enabled: true
  size: 8Gi
  storageClass: standard

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

auth:
  enabled: true
  password: "jinhyeok123"

metrics:
  enabled: true