# alertmanager:
#   alertmanagerSpec:
#     config:
#       global:
#         resolve_timeout: 5m
#       route:
#         group_by: ['alertname']
#         group_wait: 30s
#         group_interval: 5m
#         repeat_interval: 4h
#         receiver: 'slack'
#       receivers:
#       - name: 'slack'
#         slack_configs:
#         - api_url: 'https://hooks.slack.com/services/YOUR-WEBHOOK-URL'
#           channel: '#alerts'
#           text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

grafana:
  adminPassword: jinhyeok123
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: standard
  service:
    type: NodePort

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
     - name: Prometheus
       type: prometheus
       access: proxy
       url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
       isDefault: true
