apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup
  namespace: database
spec:
  schedule: "0 3 * * *" # 매일 새벽 3시
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: bitnami/redis:latest
            command: ["redis-cli"]
            args: ["--rdb", "/backup/redis-dump.rdb"]
            env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: redis-backup-pvc
